### PR TITLE
Bootstrap example using Newsweek's site as example

### PR DESCRIPTION
**Pull request by gdumani**
The following project tries to use Bootstrap exclusively for the deployment fo a Newsweek look-alike main page. 

- Bootstrap 4.4.1 and Themestr,app's tools were used in its creation.
- CSS configuration was kept to the bare minimum.

The page is responsive and compatible with most modern Browsers

### CODE REVIEW

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello! 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [x] Here goes the 'latest news' and the 'SIGN UP FOR OUR NEWSLETTER' on the right side. And on the left side, ends with the 'FEATURED STORIES'. Consider following the original design. 





- [x] Consider adding `Bold` tag to every subtitle as the original page.
- [x] The main titles like 'FEATURED STORIES', 'Top story' etc are in Gray Bold. Consider fixing this.
- [x] Missing 'SIGN UP FOR OUR NEWSLETTER' section here, Consider add it.



- [x] The first image is bigger than the others on the original page, consider fixing this.





- [x] Consider made more margin in 'editor's pick' and in the slideshows.


- [x] 'HEROES OF THE PANDEMIC' is missing, consider add it.
- [x] All the subtitles are links, consider fix this.
- [x] 'Newsweek' logo is a link. 
- [x] Consider made more margin-top below the image, most of them are almost overlapping on the image. 
- [x] Missing a division line on the footer, consider adding it.



- [x] What is this? Consider fix it, and if you don't need then remove it.

Screenshot from 2020-04-22 20-57-52

Medium Screen:

- [x] Made more margin on the titles, the font size bigger and bold as the original page.


- [x] Made more margin on the left and right side of the section, more margin between 'subscribe' and the 'hamburger' icon.


- [x] On the 'opinion', 'the debate' and 'latest news' sections, the images are too big, and the margin-top is missing is almost overlapping with the last section. Consider made these changes. 



- [x] The 'subscribe' button has to be bigger as the original page, on 'subscribe', and 'newsletter' sections.

Small version:

- [ ] The order of the structure is: "top story", 'FEATURED STORIES', 'OPINION', 'THE DEBATE', 'MORE STORIES', 'HEROES OF THE PANDEMIC', 'CULTURE & TRAVEL' and 'LATEST NEWS' Consider follow the same structure as the original page. 

- [x] Consider fix 'more stories' and 'opinion' section as the original page.



- [x] Consider made the distribution and proportion 'in the entire magazine' section as the original page.





- [x] The images here are too big, consider fixing this as the original page.




- [ ] The 'subscribe' and 'newsletter' section is center including the elements, consider fix this as the original page is.

- [x] Consider fix the date on the footer here, and respect the margins as the original page have.


- [ ] Respecting the CSS files, I can not make too much review, because you only write 25 lines for the entire project. Maybe when you fix the 'custombootstrap.css' file I can see more CSS styles to review. 

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by gdumani** [comment]
the custom-bootstrap.css is a file generated by Themestr.app used to change certain parameters in bootstraps defaults. The purpose here has to see how far I could go without using CSS in replicating the example page. The modifications applied are the following:
{
  "$red": "#f72210",
  "$blue": "#3581f4",
  "$primary": "$red",
  "$secondary": "$blue",
  "$light": "$gray-200",
  "$dark": "$gray-600",
  "$font-size-base": "0.9375rem",
  "$h1-font-size": "$font-size-base * 1.5",
  "$h2-font-size": "$font-size-base * 1.6",
  "$h3-font-size": "$font-size-base * 1.33",
  "$h4-font-size": "$font-size-base * 1.133"
}

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @gdumani, congratulations for fixing all the changes requested by the previous TSE :smile: 
Go ahead and merge to master.

Good luck with your next project :+1: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Pull request merged**
